export const SET_LIKES = 'SET_LIKES';
export const RESET_STATE = "RESET_STATE";
export const CHARACTERS_REQUEST = "CHARACTERS_REQUEST";
export const CHARACTERS_ERROR = "CHARACTERS_ERROR";
export const CHARACTERS_SUCCESS = "CHARACTERS_SUCCESS";
